apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
  ownerReferences: # used for finding which SchemaRegistry does this Deployment belong to
    - apiVersion: apps/v1
      kind: SchemaRegistry
      name: ""
      uid: ""
spec:
  selector:
    matchLabels: {}
  replicas: 1
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - name: cp-schema-registry
          image: ""
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP