apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schemaregistries.kafka.strimzi.io
spec:
  scope: Namespaced
  group: kafka.strimzi.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
  names:
    kind: SchemaRegistry
    plural: schemaregistries
    singular: schemaregistry
    shortNames:
      - srs
      - sr
